[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dexter-manual"
authors = [{name = "Wojciech Klaudiusz Zaborowski"}]
dynamic = ["version", "description"]
